module_version: 0.1.2

tests:
    - name: Test the module with 0.12.7
      terraform_version: 0.12.7
      environment:
        TF_VAR_one: onevar

    - name: Test the submodule with 0.13.0
      project_root: api_dyno
      terraform_version: 0.13.0
      environment:
        TF_VAR_region: us-east-1
        TF_VAR_aws_region: us-east-1
        TF_VAR_dynamo_table_name: spacedata
        TF_VAR_ddb_default_rcu: 5
        TF_VAR_ddb_default_wcu: 5
        TF_VAR_aws_gateway_stage: V1

